version: '3.9'

services:
  webapp:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: my_web_app
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: my_sql_server
    environment:
      SA_PASSWORD: "admin2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my_network

networks:
  my_network: